# Introduksjon

Dette er et dokument under arbeid. 

# LOVER OG FØRINGER
## Liste over lovverk

Her plasseres en liste over aktuelt lovverk for helseregisterfeltet:


*Generelt lovverk*:

* [Helseregisterloven](https://lovdata.no/dokument/NL/lov/2014-06-20-43)
* [Lov om endringer i helseregisterloven m.m. (tilgjengeliggjøring av helsedata)](https://lovdata.no/dokument/NL/lov/2020-12-04-133)

*Lover knyttet til bestemte registre/typer registre*

* **Medisinske kvalitetsregistre**: [Forskrift om medisinske kvalitetsregistre](https://lovdata.no/dokument/SF/forskrift/2019-06-21-789), 
med kapitler om følgende temaer:
  * Opplysninger i medisinske kvalitetsregistre
  * Samtykke, informasjon, dokumentasjon mv.
  * Utlevering og annen behandling av helseopplysninger i registeret
  * Informasjonssikkerhet

* **Dødsårsaksregisteret**: [Forskrift om innsamling og behandling av helseopplysninger i Dødsårsaksregisteret (Dødsårsaksregisterforskriften)]( 
https://lovdata.no/dokument/SF/forskrift/2001-12-21-1476)




# DATA
## Om data og åpne data 

Her plasseres en liste over grunnleggende prinsipper eller føringer :

**Når man skal generere, håndtere og dele data**

* FAIR-prinsippene.
  * F - søkbarhet
  * A - tilgjengelighet
  * I - interoperable (bruk av standarder)
  * R - gjenbrukbarhet (metadata om vilkår for bruk, opphav/bearbeiding og datakvalitet)
  
For bruk av FAIR-prinsippene i praksis, se f.eks. denne veileder og veiledende 
spørsmål i den: 
https://ehelse.no/standarder/ikke-standarder/veileder-for-bruk-av-FAIR-prinsippene-for-helsedatakilder 
  
**Bearbeiding og bruk av data**

* Tidy data-prinsipper (Hadely Wickham)


# GRAFISKE PRESENTASJONER
## Standardisering av resultater årsrapporten og annet
Standarder presentasjon av resultater - se spesielt Standardiseringsdokumentet: 
https://www.kvalitetsregistre.no/artikkel/standardisering-av-resultater-til-offentliggjoring

## Fere farger
Se her: 
https://helse-nord.no/Documents/Profilhandbok/Profilprogram%20Helse%20Nord.pdf

